# Project: braintransplant-ai — File: docker-compose.yml

services:
  app:
    build:
      context: .
      args:
        BASE: "cpu"
    image: braintransplant-ai:cpu
    container_name: braintransplant-ai
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # --- Explicitly point to the Service Account Key ---
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/gcp_service_account.json
      - GCP_PROJECT_ID=fresh-myth-471317-j9
      # --- Postgres connection (app -> db) ---
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=braintransplant_ai_user
      - POSTGRES_PASSWORD=braintransplant_ai_user_password
      - POSTGRES_DB=braintransplant_ai_db
      # --- App auth ---
      - ADMIN_TOKEN=admin
      # --- LLM (current) ---
      - LLM_PROVIDER=gemini
      - LLM_MODEL=gemini-1.5-pro

    command: ["streamlit","run","src/ui/web/app.py","--server.port=8502","--server.address=0.0.0.0"]

    volumes:
      - .:/app

    ports:
      - "8502:8502"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: braintransplant-db
    restart: always
    environment:
      POSTGRES_USER: braintransplant_ai_user
      POSTGRES_PASSWORD: braintransplant_ai_user_password
      POSTGRES_DB: braintransplant_ai_db
    volumes:
      - braintransplant-ai_pgdata:/var/lib/postgresql/data:rw

volumes:
  braintransplant-ai_pgdata:
