name: Docker Hub Multi-Arch Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: github.repository == 'igorrazumny/braintransplant-ai'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: igorrazumny/braintransplant-ai:latest
          build-args: |
            CACHE_BUSTER=${{ github.run_id }}
            BASE=cpu
